from django.contrib import admin
from uploader.models import *

# Register your models here.
admin.site.register(Syllabus, SyllabusAdmin)
admin.site.register(ExamBoard, ExamBoardAdmin)
admin.site.register(ExamLevel, ExamLevelAdmin)
admin.site.register(Subject, SubjectAdmin)
admin.site.register(Resource, ResourceAdmin)
admin.site.register(Unit, UnitAdmin)
admin.site.register(UnitTopic, UnitTopicAdmin)
admin.site.register(Topic, TopicAdmin)
admin.site.register(Licence, LicenceAdmin)
admin.site.register(File, FileAdmin)
admin.site.register(Bookmark, BookmarkAdmin)
admin.site.register(Rating, RatingAdmin)
admin.site.register(TeacherProfile)
admin.site.register(StudentProfile)
admin.site.register(Message, MessageAdmin)
admin.site.register(Note, NoteAdmin)
admin.site.register(MultipleChoiceQuestion)
admin.site.register(MultipleChoiceAnswer)
admin.site.register(MultipleChoiceUserAnswer)
admin.site.register(Lesson)
admin.site.register(LessonItem)
admin.site.register(SyllabusFavourite)
admin.site.register(UnitFavourite)
admin.site.register(UnitTopicFavourite)